### ISSUE TITLE
upack.exe crashes when you forget the version parameter for the pack command

### ISSUE THREAD

**Issue by wldevries** [Inedo/upack#37]
**Summary**
The upack pack command crashes when you do not supply the version command

**Expected result**
The pack command either uses 1.0.0 as the default for version or it delivers an error message.

**Actual result**
An exception occurs and after a significant delay the program exits without producing a .upack file.

```
PS C:\MyPackage> upack pack . --name="MyPackage"

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: s
   at Inedo.UPack.UniversalPackageVersion.Parse(String s)
   at Inedo.UPack.Packaging.UniversalPackageMetadata.get_Version()
   at Inedo.ProGet.UPack.Command.ValidateManifest(UniversalPackageMetadata info)
   at Inedo.ProGet.UPack.Pack.<RunAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Inedo.ProGet.UPack.CommandDispatcher.Main(String[] args)
   at Inedo.ProGet.UPack.Program.Main(String[] args)
```

**Comment by apapadimoulis** [comment]
This should definitely error out with a message about a required version number.
