### ISSUE TITLE
upack.exe crashes for the install command when the target argument is not passed in

### ISSUE THREAD

**Issue by wldevries** [Inedo/upack#38]
**Steps to reproduce**
Try to install a package without specifying the target path
```
PS C:\Users\me\> upack install MyGroup/MyPackage 1.0.0 --source=http://progetpath
```
**Expected result**
The package is installed either in the current directory or in the directory named MyPackage.

**Actual result**
The upack.exe program crashes with the following result:
```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.Directory.CreateDirectory(String path)
   at Inedo.ProGet.UPack.Command.<UnpackZipAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Inedo.ProGet.UPack.Install.<RunAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Inedo.ProGet.UPack.CommandDispatcher.Main(String[] args)
   at Inedo.ProGet.UPack.Program.Main(String[] args)
```

**Comment by BenLubar** [comment]
As far as I can tell, this shouldn't be possible because the commit that made `--target` optional also gave it a default value: https://github.com/Inedo/upack/commit/46a7b1a62ee6eb1d4c2e95bd5849be598f485d74

Unless `Environment.CurrentDirectory` can be null, which would be very strange indeed...
