### ISSUE TITLE
'upack.exe pack' crashes

### ISSUE THREAD

**Issue by wldevries** [Inedo/upack#43]
**Version**
Upack 2.2.2.2

**Steps to reproduce**
```
> upack pack

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Inedo.ProGet.UPack.Command.ExtraArgument.GetUsage()
   at Inedo.ProGet.UPack.Command.GetUsage()
   at Inedo.ProGet.UPack.Command.GetHelp()
   at Inedo.ProGet.UPack.CommandDispatcher.ShowHelp(Command cmd)
   at Inedo.ProGet.UPack.CommandDispatcher.Main(String[] args)
   at Inedo.ProGet.UPack.Program.Main(String[] args)
```

**Expected result**
Usage information for the `pack` command.

**Comment by wldevries** [comment]
I've followed the instructions in the README.md to create a package using valid arguments. The pack command fails regardless what you pass into it.
