### ISSUE TITLE
"upack.exe install" crashes due to existing temp file 

### ISSUE THREAD

**Issue by steffen-wilke** [Inedo/upack#51]
I've got some issues when trying to install a package that was just published with the Jenkins Proget Plugin. The first time I call the command below, everything works as expected. If I do it a second time, the same exception as in #40 occurs.

After that, I',m not able to install the package to other target directories anymore due to the following exception:

**upack.exe version**
2.2.3.9

**used command (abstracted package and url names):**
upack install ci/my-package --source=http://proget.mycompany.com/upack/jenkins-test/ --target=C:\temp\upack

```
Unhandled Exception: System.IO.IOException: The file 'C:\Users\MYUSER\AppData\Local\Temp\tmp9123.tmp' already exists.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Inedo.UPack.Packaging.UniversalPackage..ctor(Stream stream, Boolean leaveOpen)
   at Inedo.UPack.Packaging.UniversalPackage..ctor(Stream stream)
   at Inedo.ProGet.UPack.Install.<RunAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Inedo.ProGet.UPack.CommandDispatcher.Main(String[] args)
   at Inedo.ProGet.UPack.Program.Main(String[] args)
```

**Comment by gdivis** [comment]
Thanks for the error report. It looks like this is caused by how the stream is getting opened. Should have a fix soon!
